// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BudgetDBContext))]
    [Migration("20260423203124_AddRabobankImport")]
    partial class AddRabobankImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Model.BudgetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Period")
                        .HasDatabaseName("idx_budgetline_category_period");

                    b.ToTable("BudgetLine", (string)null);
                });

            modelBuilder.Entity("DataAccess.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("DataAccess.Model.RabobankImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bedrag")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NaamTegenpartij")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Omschrijving")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("SaldoNaTrn")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("enum('Pending','Processed','Skipped','Duplicate')");

                    b.Property<int?>("SuggestedBudgetLineId")
                        .HasColumnType("int");

                    b.Property<string>("TegenrekeningIBAN")
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<string>("Volgnr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SuggestedBudgetLineId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("Volgnr")
                        .IsUnique()
                        .HasDatabaseName("idx_rabobankimport_volgnr");

                    b.ToTable("RabobankImport", (string)null);
                });

            modelBuilder.Entity("DataAccess.Model.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("enum('Manual','Imported','Pending','Approved','Rejected')");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Date")
                        .HasDatabaseName("idx_transaction_category_date");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("DataAccess.Model.TransactionBudgetLine", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("BudgetLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("AmountAllocated")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("TransactionId", "BudgetLineId");

                    b.HasIndex("BudgetLineId");

                    b.ToTable("TransactionBudgetLine", (string)null);
                });

            modelBuilder.Entity("DataAccess.Model.BudgetLine", b =>
                {
                    b.HasOne("DataAccess.Model.Category", "Category")
                        .WithMany("BudgetLines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.Model.Category", b =>
                {
                    b.HasOne("DataAccess.Model.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("DataAccess.Model.RabobankImport", b =>
                {
                    b.HasOne("DataAccess.Model.BudgetLine", "SuggestedBudgetLine")
                        .WithMany()
                        .HasForeignKey("SuggestedBudgetLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccess.Model.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SuggestedBudgetLine");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DataAccess.Model.Transaction", b =>
                {
                    b.HasOne("DataAccess.Model.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DataAccess.Model.TransactionBudgetLine", b =>
                {
                    b.HasOne("DataAccess.Model.BudgetLine", "BudgetLine")
                        .WithMany("TransactionBudgetLines")
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Model.Transaction", "Transaction")
                        .WithMany("TransactionBudgetLines")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DataAccess.Model.BudgetLine", b =>
                {
                    b.Navigation("TransactionBudgetLines");
                });

            modelBuilder.Entity("DataAccess.Model.Category", b =>
                {
                    b.Navigation("BudgetLines");

                    b.Navigation("SubCategories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DataAccess.Model.Transaction", b =>
                {
                    b.Navigation("TransactionBudgetLines");
                });
#pragma warning restore 612, 618
        }
    }
}
